@echo off
setlocal

cd /d "%~dp0"

if exist ".venv\Scripts\python.exe" (
    set "PY=.venv\Scripts\python.exe"
) else if exist "venv\Scripts\python.exe" (
    set "PY=venv\Scripts\python.exe"
) else (
    set "PY=python"
)

set "MODE=%~1"
if "%MODE%"=="" set "MODE=both"
set "CAMERA_DEFAULT=%~2"
if "%CAMERA_DEFAULT%"=="" set "CAMERA_DEFAULT=no-camera"

if /I not "%MODE%"=="external" if /I not "%MODE%"=="embedded" if /I not "%MODE%"=="both" (
    echo Invalid build mode: %MODE%
    echo Usage: build_pyinstaller.bat [external^|embedded^|both] [show-camera^|no-camera]
    exit /b 1
)

if /I not "%CAMERA_DEFAULT%"=="show-camera" if /I not "%CAMERA_DEFAULT%"=="no-camera" (
    echo Invalid camera default: %CAMERA_DEFAULT%
    echo Usage: build_pyinstaller.bat [external^|embedded^|both] [show-camera^|no-camera]
    exit /b 1
)

echo # Auto-generated by build_pyinstaller.bat> build_config.py
echo # Valid values: external, embedded, both>> build_config.py
echo FACES_SOURCE_MODE = "%MODE%">> build_config.py
echo # Valid values: show-camera, no-camera>> build_config.py
echo CAMERA_DEFAULT_MODE = "%CAMERA_DEFAULT%">> build_config.py

set "EXE_NAME=MythUpHello-%MODE%"

echo Build mode: %MODE%
echo Camera default: %CAMERA_DEFAULT%

echo [1/2] Checking PyInstaller...
%PY% -m pip show pyinstaller >nul 2>&1
if errorlevel 1 (
    echo PyInstaller not found. Installing...
    %PY% -m pip install pyinstaller
)

echo [2/2] Building executable...
set "HAS_FACES=0"
set "HAS_ENCODING=0"
if exist "faces" set "HAS_FACES=1"
if exist "encodings.npy" set "HAS_ENCODING=1"

if /I "%MODE%"=="external" (
    %PY% -m PyInstaller ^
        --noconfirm ^
        --clean ^
        --onefile ^
        --noconsole ^
        --name %EXE_NAME% ^
        --collect-all face_recognition_models ^
        main.py
) else if "%HAS_FACES%%HAS_ENCODING%"=="11" (
    %PY% -m PyInstaller ^
        --noconfirm ^
        --clean ^
        --onefile ^
        --noconsole ^
        --name %EXE_NAME% ^
        --add-data "faces;faces" ^
        --add-data "encodings.npy;." ^
        --collect-all face_recognition_models ^
        main.py
) else if "%HAS_FACES%%HAS_ENCODING%"=="10" (
    %PY% -m PyInstaller ^
        --noconfirm ^
        --clean ^
        --onefile ^
        --noconsole ^
        --name %EXE_NAME% ^
        --add-data "faces;faces" ^
        --collect-all face_recognition_models ^
        main.py
) else if "%HAS_FACES%%HAS_ENCODING%"=="01" (
    %PY% -m PyInstaller ^
        --noconfirm ^
        --clean ^
        --onefile ^
        --noconsole ^
        --name %EXE_NAME% ^
        --add-data "encodings.npy;." ^
        --collect-all face_recognition_models ^
        main.py
) else (
    echo Warning: no local embedded data found. Building executable without embedded faces.
    %PY% -m PyInstaller ^
        --noconfirm ^
        --clean ^
        --onefile ^
        --noconsole ^
        --name %EXE_NAME% ^
        --collect-all face_recognition_models ^
        main.py
)

if errorlevel 1 (
    echo Build failed.
    exit /b 1
)

echo.
echo Build completed. Executable: dist\%EXE_NAME%.exe
echo Authorization source mode: %MODE%
echo Camera default mode: %CAMERA_DEFAULT%
echo Launch with camera preview: dist\%EXE_NAME%.exe --show-camera
echo Launch without camera preview: dist\%EXE_NAME%.exe --no-camera
endlocal
